/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cliente;
import clases.Cuenta;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Imp_Cli;
import logica.Imp_Cuentas;
import logica.ManCliente;
import logica.ManCuenta;

/**
 *
 * @author diegomerino
 */
public class CrearCuenta extends javax.swing.JFrame {

    Imp_Cli objImpCli = new Imp_Cli();
    Imp_Cuentas objImpCue = new Imp_Cuentas();
    ManCliente objManCli = new ManCliente();
    ManCuenta objManCue = new ManCuenta();
    Cliente objCli = new Cliente();
    Cuenta objCue = new Cuenta();
    ArrayList<Cuenta> ArrayCuentas = new ArrayList<Cuenta>();
    ArrayList<Cliente> ArrayClientes = new ArrayList<Cliente>();
    ArrayList<Cliente> objArrCli = new ArrayList<Cliente>();

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        ArrayClientes = objImpCli.ImportarClientes();
        ArrayCuentas = objImpCue.ImportarCuentas();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jCueCed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCueTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jCueDep = new javax.swing.JTextField();
        jCueCre = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jCueAgre = new javax.swing.JButton();
        jUsuCed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jUsuGua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Crear Cuenta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 20));

        jCueCed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCueCedActionPerformed(evt);
            }
        });
        jPanel1.add(jCueCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 100, -1));

        jLabel2.setText("Numero de Cédula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setText("Tipo de Cuenta: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jCueTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Ahorros", "Cuenta Corriente" }));
        jCueTipo.setEnabled(false);
        jCueTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCueTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jCueTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel4.setText("Depósito Inicial");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jCueDep.setEnabled(false);
        jPanel1.add(jCueDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 80, -1));

        jCueCre.setText("Crear");
        jCueCre.setEnabled(false);
        jCueCre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCueCreActionPerformed(evt);
            }
        });
        jPanel1.add(jCueCre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 160));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 400, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jCueAgre.setText("Agregar Usuario");
        jCueAgre.setEnabled(false);
        jCueAgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCueAgreActionPerformed(evt);
            }
        });

        jUsuCed.setEnabled(false);
        jUsuCed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuCedActionPerformed(evt);
            }
        });

        jLabel5.setText("# Cédula");

        jUsuGua.setText("Guardar");
        jUsuGua.setEnabled(false);
        jUsuGua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuGuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCueAgre))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jUsuGua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jUsuCed))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCueAgre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUsuCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jUsuGua)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 170));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 450, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCueCedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCueCedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCueCedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        objCli = this.objManCli.BuscarCliente(ArrayClientes, this.jCueCed.getText());
        try {
            if (objCli.getCedula().equals(this.jCueCed.getText())) {
                this.jCueTipo.setEnabled(true);
                this.jCueDep.setEnabled(true);
                this.jCueCre.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Cliente no existe\n"
                    + "¿Desea Crearlo?");
            if (JOptionPane.YES_OPTION == 0) {
                CrearCliente objCreCli = new CrearCliente();
                objCreCli.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCueTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCueTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCueTipoActionPerformed

    private void jUsuCedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuCedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsuCedActionPerformed

    private void jCueCreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCueCreActionPerformed
        // TODO add your handling code here:
        Formatter fmt = new Formatter();
        int numCue = ArrayCuentas.size();
        fmt.format("%08d", numCue);
        String cuenta= String.valueOf(numCue);
        int tipo =0;
        if (this.jCueTipo.getSelectedIndex()==0) {
            tipo = 1;
        }else if (this.jCueTipo.getSelectedIndex()==1){
            tipo = 2;
        }
        objArrCli.add(objCli);
        objCue = objManCue.CrearCuenta(cuenta, tipo, Double.parseDouble(this.jCueDep.getText()), objArrCli);
        ArrayCuentas.add(objCue);
        System.out.println(objCue.toString());
        this.jCueAgre.setEnabled(true);
//        try {
//            objManCue.GuardarCuentaClientes(ArrayCuentas);
//        } catch (IOException ex) {
//            Logger.getLogger(CrearCuenta.class.getName()).log(Level.SEVERE, null, ex);
//        } finally {
//            this.jCueAgre.setEnabled(true);
//        }
    }//GEN-LAST:event_jCueCreActionPerformed

    private void jUsuGuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuGuaActionPerformed
        // TODO add your handling code here:
        objCli = objManCli.BuscarCliente(ArrayClientes, this.jUsuCed.getText());
        try{
            objArrCli.add(objCli);
            System.out.println(objCue.toString());
        } catch (Exception e){
            
        } finally{
            
        }
    }//GEN-LAST:event_jUsuGuaActionPerformed

    private void jCueAgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCueAgreActionPerformed
        // TODO add your handling code here:
        this.jUsuCed.setEnabled(true);
        this.jUsuGua.setEnabled(true);
    }//GEN-LAST:event_jCueAgreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCueAgre;
    private javax.swing.JTextField jCueCed;
    private javax.swing.JButton jCueCre;
    private javax.swing.JTextField jCueDep;
    private javax.swing.JComboBox<String> jCueTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jUsuCed;
    private javax.swing.JButton jUsuGua;
    // End of variables declaration//GEN-END:variables
}
