/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cliente;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Imp_Cli;
import logica.ManCliente;

/**
 *
 * @author diegomerino
 */
public class CrearCliente extends javax.swing.JFrame {
    Imp_Cli objImpCli = new Imp_Cli();
    ManCliente objManCli = new ManCliente();
    ArrayList<Cliente> ArrayClientes = new ArrayList<Cliente>();
    Cliente objCli = new Cliente();
    /**
     * Creates new form CrearCliente
     */
    public CrearCliente() {
        ArrayClientes = objImpCli.ImportarClientes();
        setTitle("Crear Cuenta");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCrearCedula = new javax.swing.JTextField();
        jCrearNombre = new javax.swing.JTextField();
        jCrearApellido = new javax.swing.JTextField();
        jCrearDireccion = new javax.swing.JTextField();
        jCrearGuardar = new javax.swing.JButton();
        jCrearSalir = new javax.swing.JButton();
        jCrearValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Crear Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Número de Cédula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setText("Dirección:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jCrearCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(jCrearCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 6, 130, -1));

        jCrearNombre.setEnabled(false);
        jCrearNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jCrearNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, -1));

        jCrearApellido.setEnabled(false);
        jPanel1.add(jCrearApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, -1));

        jCrearDireccion.setEnabled(false);
        jPanel1.add(jCrearDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));

        jCrearGuardar.setText("Guardar");
        jCrearGuardar.setEnabled(false);
        jCrearGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jCrearGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jCrearSalir.setText("Salir");
        jCrearSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jCrearSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jCrearValidar.setText("Validar");
        jCrearValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearValidarActionPerformed(evt);
            }
        });
        jPanel1.add(jCrearValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 330, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCrearCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearCedulaActionPerformed
        // TODO add your handling code here:
        if (jCrearCedula.getText().isEmpty() == true){
            
        }
    }//GEN-LAST:event_jCrearCedulaActionPerformed

    private void jCrearNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrearNombreActionPerformed

    private void jCrearGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearGuardarActionPerformed
        // TODO add your handling code here:
        objCli = objManCli.CrearCliente(this.jCrearCedula.getText(), this.jCrearNombre.getText(), this.jCrearApellido.getText());
        ArrayClientes.add(objCli);
        try{
            objManCli.GuardarClientes(ArrayClientes);
        } catch (IOException ex) {
            Logger.getLogger(CrearCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCrearGuardarActionPerformed

    private void jCrearValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearValidarActionPerformed
        // TODO add your handling code here:
        try {
            objCli = objManCli.BuscarCliente(ArrayClientes, jCrearCedula.getText());
            if (objCli.getCedula() == null) {
                this.jCrearGuardar.setEnabled(true);
                this.jCrearNombre.setEnabled(true);
                this.jCrearApellido.setEnabled(true);
                this.jCrearDireccion.setEnabled(true);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Cliente ya existe");
            }
        }
        catch (Exception e){
            
        }
    }//GEN-LAST:event_jCrearValidarActionPerformed

    private void jCrearSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCrearSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jCrearApellido;
    private javax.swing.JTextField jCrearCedula;
    private javax.swing.JTextField jCrearDireccion;
    private javax.swing.JButton jCrearGuardar;
    private javax.swing.JTextField jCrearNombre;
    private javax.swing.JButton jCrearSalir;
    private javax.swing.JButton jCrearValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
