/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cajero;
import clases.Cliente;
import clases.Cuenta;
import clases.Transaccion;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Imp_Caj;
import logica.Imp_Cli;
import logica.Imp_Cuentas;
import logica.Imp_Tra;
import logica.ManCajero;
import logica.ManCliente;
import logica.ManCuenta;
import logica.ManTransaccion;

/**
 *
 * @author Administrador
 */
public class Deposito extends javax.swing.JFrame {

    Imp_Cli objImpCli = new Imp_Cli();
    Imp_Cuentas objImpCue = new Imp_Cuentas();
    Imp_Caj objImpCaj = new Imp_Caj();
    Imp_Tra objImpTra = new Imp_Tra();
    ManCajero objManCaj = new ManCajero();
    ManCliente objManCli = new ManCliente();
    ManCuenta objManCue = new ManCuenta();
    ManTransaccion objManTra = new ManTransaccion();
    ArrayList<Cliente> ArrayClientes = new ArrayList<Cliente>();
    ArrayList<Cuenta> ArrayCuentas = new ArrayList<Cuenta>();
    ArrayList<Cajero> ArrayCajeros = new ArrayList<Cajero>();
    ArrayList<Transaccion> ArrayTransacciones = new ArrayList<Transaccion>();
    Cuenta objCue = new Cuenta();
    Cliente objCli = new Cliente();
    Cajero objCaj = new Cajero();
    Transaccion objTra = new Transaccion();
    /**
     * Creates new form Deposito
     */
    public Deposito() {
        initComponents();
        ArrayClientes = objImpCli.ImportarClientes();
        ArrayCuentas = objImpCue.ImportarCuentas();
        ArrayCajeros = objImpCaj.ImportarCajeros();
        ArrayTransacciones = objImpTra.ImportarTransaccion();
        setTitle("Depósito");
        objCaj = objManCaj.BuscarCajero(ArrayCajeros, "987");
        this.jcajID.setText(objCaj.getId_cajero());
        this.jcajNom.setText(objCaj.getNombre());
        this.jcajApe.setText(objCaj.getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jnumCue = new javax.swing.JTextField();
        jverificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcliNom = new javax.swing.JTextField();
        jcliApe = new javax.swing.JTextField();
        jcliCue = new javax.swing.JTextField();
        jaceptar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jdepCed = new javax.swing.JTextField();
        jdepNom = new javax.swing.JTextField();
        jdepApe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdepCan = new javax.swing.JLabel();
        jdeposito = new javax.swing.JTextField();
        jdepCon = new javax.swing.JButton();
        jdepDeposito = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jnumTra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcajNom = new javax.swing.JTextField();
        jcajApe = new javax.swing.JTextField();
        jcajID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jnumCue.setText("# de Cuenta");
        jnumCue.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jnumCue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnumCueMouseClicked(evt);
            }
        });
        jnumCue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnumCueActionPerformed(evt);
            }
        });
        getContentPane().add(jnumCue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 76, -1));

        jverificar.setText("Verificar");
        jverificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jverificarActionPerformed(evt);
            }
        });
        getContentPane().add(jverificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel1.setText("Deposito");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 20));

        jLabel2.setText("Datos del Titular");

        jcliNom.setText("Nombre");
        jcliNom.setEnabled(false);
        jcliNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcliNomActionPerformed(evt);
            }
        });

        jcliApe.setText("Apellido");
        jcliApe.setEnabled(false);

        jcliCue.setText("Tipo de Cuenta");
        jcliCue.setEnabled(false);

        jaceptar.setText("Aceptar");
        jaceptar.setEnabled(false);
        jaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcliNom, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jcliApe, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jaceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcliCue, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcliNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcliApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcliCue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jaceptar)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 220, 150));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdepCed.setEnabled(false);
        jPanel2.add(jdepCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 76, -1));

        jdepNom.setEnabled(false);
        jPanel2.add(jdepNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 93, -1));

        jdepApe.setEnabled(false);
        jPanel2.add(jdepApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 93, -1));

        jLabel3.setText("# Cédula");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 60, -1));

        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, -1));

        jLabel5.setText("Apellido");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 20));

        jdepCan.setText("Valor a depositar");
        jPanel2.add(jdepCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jdeposito.setEnabled(false);
        jPanel2.add(jdeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 93, -1));

        jdepCon.setText("Comprobar");
        jdepCon.setEnabled(false);
        jdepCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdepConActionPerformed(evt);
            }
        });
        jPanel2.add(jdepCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 42, -1, -1));

        jdepDeposito.setText("Depositar");
        jdepDeposito.setEnabled(false);
        jdepDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdepDepositoActionPerformed(evt);
            }
        });
        jPanel2.add(jdepDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 240));

        jLabel6.setText("Transaccion #:");

        jnumTra.setEnabled(false);

        jLabel7.setText("Atendido por:");

        jcajNom.setEnabled(false);
        jcajNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcajNomActionPerformed(evt);
            }
        });

        jcajApe.setEnabled(false);
        jcajApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcajApeActionPerformed(evt);
            }
        });

        jcajID.setEnabled(false);
        jcajID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcajIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jcajNom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcajApe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcajID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jnumTra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jnumTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcajNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcajApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcajID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 390, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnumCueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnumCueActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jnumCueActionPerformed

    private void jcliNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcliNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcliNomActionPerformed

    private void jverificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jverificarActionPerformed
        // TODO add your handling code here:
        objCue = objManCue.BuscarCuenta(ArrayCuentas, jnumCue.getText());
        try {
            if (objCue.getNumero().equals(jnumCue.getText())) {
                this.jcliNom.setText(objCue.getCliente().getNombre());
                this.jcliApe.setText(objCue.getCliente().getApellido());
                if (objCue.getTipo() == 1) {
                    this.jcliCue.setText("Cuenta Ahorros");
                }
                if (objCue.getTipo() == 2) {
                    this.jcliCue.setText("Cuenta Corriente");
                }
                this.jaceptar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Cuenta no Existe");
            this.jcliNom.setText("");
            this.jcliApe.setText("");
            this.jcliCue.setText("");
            this.jdepCed.setEnabled(false);
            this.jdepNom.setEnabled(false);
            this.jdepApe.setEnabled(false);
            this.jdeposito.setEnabled(false);
            this.jaceptar.setEnabled(false);
        }

    }//GEN-LAST:event_jverificarActionPerformed

    private void jdepConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdepConActionPerformed
        // TODO add your handling code here:
        objCli = objManCli.BuscarCliente(ArrayClientes, jdepCed.getText());
        try {
            if (Integer.parseInt(objCli.getCedula()) == Integer.parseInt(jdepCed.getText())) {
                this.jdepNom.setText(objCli.getNombre());
                this.jdepApe.setText(objCli.getApellido());
                this.jdepDeposito.setEnabled(true);
                this.jdeposito.setEnabled(true);
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Ingrese Datos del Depositante");
                this.jdepNom.setText("");
                this.jdepApe.setText("");
                this.jdepNom.setEnabled(true);
                this.jdepApe.setEnabled(true);
                this.jdeposito.setEnabled(true);
                this.jdepDeposito.setEnabled(true);
        }
    }//GEN-LAST:event_jdepConActionPerformed

    private void jdepDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdepDepositoActionPerformed
        // TODO add your handling code here:
        try{
//            if (Integer.parseInt(objCli.getCedula()) != Integer.parseInt(jdepCed.getText())) {
//                objCli = objManCli.CrearCliente(jdepCed.getText(), jdepNom.getText(), jdepApe.getText());
//                ArrayClientes.add(objCli);
//            }
            objCli = objManCli.CrearCliente(jdepCed.getText(), jdepNom.getText(), jdepApe.getText());
            boolean auxCli = true;
            if (auxCli != objManCli.ComprobarCliente(ArrayClientes, objCli.getCedula())) {
                ArrayClientes.add(objCli);
            }
            objCue = objManCue.DepositoCuenta(objCue, Double.parseDouble(this.jdeposito.getText()));
            objTra = objManTra.CrearTransaccion(objCli, objCaj, objCue, ArrayTransacciones);
            JOptionPane.showMessageDialog(rootPane, "Deposito exitoso");
            this.jnumTra.setText(String.valueOf(objTra.getId_transaccion()));
            ArrayTransacciones.add(objTra);
            ArrayCuentas.set(ArrayCuentas.indexOf(objCue), objCue);
            try {
                objManTra.GuardaTransaccion(ArrayTransacciones);
                objManCue.GuardarCuenta(ArrayCuentas);
                objManCli.GuardarClientes(ArrayClientes);
            } catch (IOException ex) {
                Logger.getLogger(Deposito.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch (NumberFormatException e){   
        }
        finally{
            //TextFields en vacio de nuevo
            this.jnumCue.setText("");
            this.jdepCed.setText("");
            this.jdepNom.setText("");
            this.jdepApe.setText("");
            this.jcliNom.setText("");
            this.jcliApe.setText("");
            this.jcliCue.setText("");
            this.jdeposito.setText("");
            //Desactivar Botones
            this.jaceptar.setEnabled(false);
            this.jdepDeposito.setEnabled(false);
            this.jdepCon.setEnabled(false);
            //Desactivar TextFields
            this.jdepCed.setEnabled(false);
            this.jdepNom.setEnabled(false);
            this.jdepApe.setEnabled(false);
            this.jdeposito.setEnabled(false);
        }
    }//GEN-LAST:event_jdepDepositoActionPerformed

    private void jcajIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcajIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcajIDActionPerformed

    private void jaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaceptarActionPerformed
        // TODO add your handling code here:
        this.jdepCon.setEnabled(true);
        this.jdepCed.setEnabled(true);
    }//GEN-LAST:event_jaceptarActionPerformed

    private void jnumCueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnumCueMouseClicked
        // TODO add your handling code here:
        this.jnumCue.setText("");
    }//GEN-LAST:event_jnumCueMouseClicked

    private void jcajApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcajApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcajApeActionPerformed

    private void jcajNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcajNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcajNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jaceptar;
    private javax.swing.JTextField jcajApe;
    private javax.swing.JTextField jcajID;
    private javax.swing.JTextField jcajNom;
    private javax.swing.JTextField jcliApe;
    private javax.swing.JTextField jcliCue;
    private javax.swing.JTextField jcliNom;
    private javax.swing.JTextField jdepApe;
    private javax.swing.JLabel jdepCan;
    private javax.swing.JTextField jdepCed;
    private javax.swing.JButton jdepCon;
    private javax.swing.JButton jdepDeposito;
    private javax.swing.JTextField jdepNom;
    private javax.swing.JTextField jdeposito;
    private javax.swing.JTextField jnumCue;
    private javax.swing.JTextField jnumTra;
    private javax.swing.JButton jverificar;
    // End of variables declaration//GEN-END:variables
}
